### ISSUE TITLE
New tags for qrtr, rmtfs, pd-mapper & tqftpserv

### ISSUE THREAD

**Issue by JamiKettunen** [andersson/qrtr#20]
This helps with getting them officially packaged on Linux distros, but there haven't been new tags on these repos since ~2017.

**Comment by JamiKettunen** [comment]
@andersson would you mind taking a look at this when you have time?

**Comment by OrionMoonclaw** [comment]
I second that, would be nice to finally get these packages into void

**Comment by JamiKettunen** [comment]
All of them now have a `v1.0` tag, thank you!
